spring.application.name=Backend

server.port = 8090

spring.datasource.url=jdbc:postgresql://localhost:5432/Tingeso_proyecto1
spring.datasource.username=victorvaraspro
spring.datasource.password=hola2020
spring.jpa.hibernate.ddl-auto=update
